name: intercept.prism
include:
  - path: ../compose.db.yml
services:
  intercept.prism:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-release-stage
    ports:
      - 7000:7000


